name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build grpcio wheels on ${{ matrix.os }}, for Python ${{ matrix.python_build_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macOS-12" ]
        python_build_version: [ "cp38", "cp39", "cp310", "cp311" ]

    steps:
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      
      - name: Download latest grpcio stable tarball
        run: |
          pip download --no-binary grpcio grpcio
          tar xf *.tar.gz
          
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.9.0

      - name: Build wheels
        run: |
          cd grpcio-*/
          python -m cibuildwheel --output-dir ../wheelhouse
        env:
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_TEST_SKIP: "*_arm64"
          CIBW_BUILD: "${{ matrix.python_build_version }}-macosx_arm64"
          CIBW_BUILD_FRONTEND: pip
          CIBW_ENVIRONMENT_MACOS: "GRPC_PYTHON_BUILD_WITH_CYTHON=1"
          CIBW_BEFORE_BUILD: "pip install -r requirements.txt"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
